# Compare bcbio/umccrise runs

## Running on Raijin/Gadi


### Step 1: Grab an interactive node {-}

* Most memory is for `bcftools isec`

```
qsub -I -q normalbw -l ncpus=28,walltime=02:00:00,mem=80gb
```


### Step 2: Create woof run environment {-}

```
source /g/data3/gx8/extras/woof/load_woof.sh
```


### Step 3: Run woof compare {-}

* Supports only SNVs/INDELs for now.

```bash
# compare bcbio runs
woof compare --sample sample_label path/to/run1/final path/to/run2/final

# compare umccrise runs
woof compare --sample sample_label path/to/run1/umccrised/sample path/to/run2/umccrised/sample
```

* The above will create the following directory structure (example):

```
|-- final
|   |-- 2016.249.17.MH.P033
|   |   |-- bcftools_isec
|   |   |-- vcf_counts
|   |   |-- vcf_eval
|   |   `-- vcf_pass
|   `-- CUP-Pairs8
|       |-- bcftools_isec
|       |-- vcf_counts
|       |-- vcf_eval
|       `-- vcf_pass
`-- work
    |-- 2016.249.17.MH.P033
    |   |-- cromwell-executions
    |   |-- cromwell-workflow-logs
    |   |-- cromwell_config.conf
    |   |-- cromwell_inputs.json
    |   |-- cromwell_log.log
    |   |-- cromwell_meta.json
    |   |-- cromwell_opts.json
    |   |-- cromwell_samples.tsv
    |   |-- persist
    |   `-- wdl
    `-- CUP-Pairs8
        |-- cromwell-executions
        |-- cromwell-workflow-logs
        |-- cromwell_config.conf
        |-- cromwell_inputs.json
        |-- cromwell_log.log
        |-- cromwell_meta.json
        |-- cromwell_opts.json
        |-- cromwell_samples.tsv
        |-- persist
        `-- wdl
```

The final evaluation results are in `final/<sample>/vcf_eval/<vcf_type>/<ALL-or-PASS>/eval_stats.tsv`

### Step 4: Run woof report {-}

```bash
woof report -w path/to/woof/final --r1 <run1_label> --r2 <run2_label>
```

## Multi-Sample Mode

If you want to run `woof compare` on multiple samples (say, A & B), you can hack it in the following (relatively) simple way:

`woof compare --justprep path/to/run1/A/final path/to/run2/A/final -s SAMPLE_A -o woof`
`woof compare --justprep path/to/run1/B/final path/to/run2/B/final -s SAMPLE_B -o woof`

Each of the above runs prints out a cromwell command, and 'just prepares' a directory structure like the following:

```
woof
├── final/ # empty
└── work
    ├── SAMPLE_A
    │   ├── cromwell_config.conf
    │   ├── cromwell_inputs.json
    │   ├── cromwell_opts.json
    │   ├── cromwell_samples.tsv
    │   └── wdl
    │       ├── compare.wdl
    │       └── tasks/[...]
    └── SAMPLE_B
        ├── cromwell_config.conf
        ├── cromwell_inputs.json
        ├── cromwell_opts.json
        ├── cromwell_samples.tsv
        └── wdl
            ├── compare.wdl
            └── tasks/[...]
```

The `cromwell_samples.tsv` file contains rows with the sample name (e.g. `SAMPLE_A`), VCF name (e.g. `ensemble`), 
and paths to VCF1 and VCF2. You need to simply concatenate those files for each sample you want into one, then run the Cromwell command:

```
cd woof/final/work/SAMPLE_A
cat ../SAMPLE_B/cromwell_samples.tsv >> cromwell_samples.tsv

cromwell -Xms1g -Xmx3g run -Dconfig.file=cromwell_config.conf \
  -DLOG_LEVEL=ERROR -DLOG_LEVEL=WARN \
  --metadata-output cromwell_meta.json \
  --options cromwell_opts.json \
  --inputs cromwell_inputs.json \
  wdl/compare.wdl 2>&1 | tee -a cromwell_log.log
```

That would fill up the `final` directory shown in the above file tree.

## Diagram


```{r gr1}
set.seed(42)

ndf <- 
  tribble(
    ~id, ~label, ~type,
    1, "vcf1", "file",
    2, "vcf2", "file",
    3, "bcftools-view-f", "command",
    4, "vcf1_pass", "file",
    5, "vcf2_pass", "file",
    6, "bcftools-isec", "command",
    7, "FP-FN-TP", "file",
    8, "FP-FN-TP_pass", "file",
    9, "count-vars", "command",
    10, "counts", "file",
    11, "counts_pass", "file") %>% 
  mutate(
    fillcolor = case_when(
      type == "file" ~ "lightblue",
 
           type == "command" ~ "#f48f42",
      TRUE ~ "#eef442"
    ),
    fontcolor = "black")

edf <- 
  create_edge_df(
    from = c(1, 2, 3, 3, 1, 2, 4, 5, 6, 6, 1, 2, 4, 5, 9, 9),
    to =   c(3, 3, 4, 5, 6, 6, 6, 6, 7, 8, 9, 9, 9, 9, 10, 11)
  )


create_graph(nodes_df = ndf, edges_df = edf) %>% 
  set_node_attrs(
    node_attr = "fontsize",
    values = "8"
  ) %>% 
  render_graph(layout = "tree")
```


