Cromwell
--------

## Cromwell on AWS Batch

### Requirements
* S3 bucket for input and output
* EC2 launch template for customising EC2 instances
* EC2 instance for Cromwell server
* AWS Batch
    - Compute environment
    - Job queue

#### S3 bucket
* Use cf template
  [here](https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/templates/aws-genomics-s3.template.yaml)

#### EC2 Launch Template
* Use cf template
  [here](https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/templates/aws-genomics-launch-template.template.yaml)
* Has a LaunchTemplateID under Outputs (e.g. `lt-12345`)

#### IAM Roles
* Use cf template
  [here](https://github.com/aws-samples/aws-genomics-workflows/blob/master/src/templates/aws-genomics-iam.template.yaml)
* Contains `BatchServiceRoleArn`, `BatchInstanceProfileArn`,
  `BatchSpotFleetRoleArn` and `BatchJobRoleArn` under Outputs

#### AWS Batch

* Helps you run batch jobs on AWS Cloud (d'oh)
* Submit jobs to the queue, specifying app to run and CPU/mem reqs
* Responsible for launching the appropriate quantity 
  and types of EC2 instances needed to run the jobs

* Manages:
  - Job definitions: Docker, vCPUs, mem etc.
  - Job queues
  - Compute environments: EC2 management
    
* Job queues `<->` one or more compute environments
* Compute environment `<->` one or more job queues



